language: ruby
env:
  global:
    - GIT_COMITTER_NAME: "Tomohiro Suwa"
    - GIT_COMITTER_EMAIL: "neoen.gsn@gmail.com"
    - GIT_AUTHOR_NAME: "Tomohiro Suwa"
    - GIT_AUTHOR_EMAIL: "neoen.gsn@gmail.com"
    - secure: "c2qFCbpu+uBqemHlTFzcDInrlc+WLCqgL9mqWvJFeAdks/J0dk3sj0NUgfsUotE6SXLVg/PFBKpOgMyrrRbzDe9fzV81tqifboK/a/Gf37jH8+l2b3Q0e/odTvzl97XaEgRYdlev5GKIThAyFv2fgx5epZ+cMbybAdOkooNJ730="
before_script:
  - git clone --quiet https://github.com/tsuwatch/tsuwatch.github.io build
script:
  - bundle exec middleman build
after_success:
  - cd build
  - git init
  - git add -A
  - git commit -m "Update from Travis CI"
  - 'git push --quiet https://$GH_TOKEN@github.com/tsuwatch/tsuwatch.github.io 2> /dev/null'
branches:
  only:
    - source
