language: ruby
env:
  global:
    - GIT_COMMITTER_NAME: "Tomohiro Suwa"
    - GIT_COMMITTER_EMAIL: "neoen.gsn@gmail.com"
    - GIT_AUTHOR_NAME: "Tomohiro Suwa"
    - GIT_AUTHOR_EMAIL: "neoen.gsn@gmail.com"
    - secure: "Q7cvcKqPH+rrX77oUI9aBycBTNiiSsT4r5id0Qrrm68HPTn9ZP0ri3TWPZ+dcuFXhQwkGrASZbZpr2TtoVMuYrHBHdL9W+dlysijHWRVQvqEUmtymuRXqVa9loC++9O6CdZpRECqCjM63O4bMAu2N7LzEkKQ2SB+NF9OjEUzYjw="
script:
  - bundle exec middleman build
after_success:
  - cd build
  - echo "task :default" > Rakefile
  - git init
  - git add -A
  - git commit -m "Update from Travis CI"
  - 'git push --quiet https://$GH_TOKEN@github.com/tsuwatch/tsuwatch.github.io master -f'
branches:
  only:
    - source
